name:         'arp242.net'
url:          'https://www.arp242.net'
author:       'Martin Tournoij'
markdown:     'kramdown'
highlighter:  'none'
includes_dir: ''
future:       true
strict_front_matter: true

defaults: [
  {
    scope:  {path: '_posts'},
    values: {layout: 'post', permalink: '/:title.html'},
  },
  {
    scope:  {path: '_drafts'},
    values: {layout: 'post', permalink: '/draft/:title.html'},
  },
]

include: ['_redirects', '.well-known']
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'css',
  'the-art-of-unix-programming/base.css',
  'the-art-of-unix-programming/base.js',
  'the-art-of-unix-programming/hello-css.min.css',
  'the-art-of-unix-programming/readon.js',
  '.vim-hl']
