// Generated by CoffeeScript 1.7.1
(function() {
  var get;

  jQuery.fn.empty = function() {
    return jQuery.trim($(this).val()) === '';
  };

  jQuery.fn.highlight = function() {
    var elem, orig;
    if (this.hasClass('js-highlight')) {
      return;
    }
    elem = this;
    elem.addClass('js-highlight');
    orig = elem.css('background-color');
    return elem.animate({
      backgroundColor: '#00dc3e'
    }, {
      duration: 400,
      done: function() {
        return (function() {
          return elem.animate({
            backgroundColor: orig
          }, {
            duration: 400,
            done: function() {
              return elem.removeClass('js-highlight');
            }
          });
        }).timeout(200);
      }
    });
  };

  get = function(cb) {
    return jQuery.ajax({
      url: "http://comments.arp242.net/" + (window.location.pathname.split('/').pop().replace(/\.html$/, '')),
      type: 'get',
      dataType: 'json',
      success: function(data) {
        if (!data.success) {
          return;
        }
        $('.comments-list').html('');
        data.comments.forEach(function(c) {
          return $('.comments-list').append("<h3>" + c.name + " had time to spare on " + c.posted + ", and wrote:</h3>\n<div>" + c.text + "</div>");
        });
        if (cb) {
          return cb.call(null);
        }
      }
    });
  };

  $('.feedbackform form').on('submit', function(e) {
    if (!('withCredentials' in new XMLHttpRequest)) {
      return alert('IE8 and lower doesn\'t work. Sorry about that :-(');
    }
    e.preventDefault();
    if ($('#comment-name').empty()) {
      return alert('You must fill in your name');
    }
    if ($('#comment-text').empty()) {
      return alert('You must write a comment');
    }
    if (jQuery.trim($('#turingtest').val()) !== '42') {
      return alert('You failed the Turing test (you didn\'t enter 42)');
    }
    return jQuery.ajax({
      url: $(this).attr('action'),
      type: $(this).attr('method'),
      data: $(this).serialize(),
      dataType: 'json',
      success: (function(_this) {
        return function(data) {
          if (!data.success) {
            return alert("Sorry, there was an error: `" + data.err + "'");
          }
          $(_this).find('input, textarea').val('');
          return get(function() {
            return $('.comments-list div:last').highlight();
          });
        };
      })(this)
    });
  });

  if ($('.weblog-comments').length > 0) {
    get();
  }

}).call(this);
