# Netlify sets cache to 0 to allow rollbacks, but this content isn't going to
# change so just cache it.
[[headers]]
	for = "*.woff2"
	[headers.values]
		Cache-Control = "public, max-age=7776000"  # 90 days
[[headers]]
	for = "*.jpg"
	[headers.values]
		Cache-Control = "public, max-age=1209600"  # 14 days

[[headers]]
	for = "*.txt"
	[headers.values]
		Content-Type = "text/plain; charset=UTF-8"
[[headers]]
	for = "*.pub"
	[headers.values]
		Content-Type = "text/plain; charset=UTF-8"
