#!/bin/sh

mkdir /tmp/ttftrim
cp ~/code/arp242.net/_fonts/*.woff2 /tmp/ttftrim
cd /tmp/ttftrim

for f in *.woff2; do
	woff2_decompress "$f"
	f2="${f%.woff2}.ttf"
	~/code/ttftrim/ttftrim "${f2}" "${f2}" ~/code/arp242.net
	woff2_compress "$f2"
done

mv *.woff2 ~/code/arp242.net/fonts
rm -r /tmp/ttftrim
