#!/usr/bin/env php
<span class="Special">&lt;?php</span>

<span class="Comment">/**</span>
<span class="Comment"> * Make a temporary file or directory in $prefix</span>
<span class="Comment"> *</span>
<span class="Comment"> * If $prefix is Null, sys_get_temp_dir() is used</span>
<span class="Comment"> *</span>
<span class="Comment"> * The template can be any file name, all sequences of two or more subsequent</span>
<span class="Comment"> * X's are replaced by random alphanumeric characters</span>
<span class="Comment"> *</span>
<span class="Comment"> * If $dir is True, a directory is created</span>
<span class="Comment"> *</span>
<span class="Comment"> * A MktempError is thrown if an error occurs</span>
<span class="Comment"> *</span>
<span class="Comment"> * We return the full path to the created file or directory.</span>
<span class="Comment"> *</span>
<span class="Comment"> * This implementation is written by Martin Tournoij &lt;martin@arp242.net&gt;, while</span>
<span class="Comment"> * peeking at FreeBSD's implementation of mkstemp (src/lib/libc/stdio/mktemp.c)</span>
<span class="Comment"> * http://www.arp242.net/php-mktemp.html</span>
<span class="Comment"> */</span>
<span class="Statement">function</span> mktemp($template=<span class="Constant">Null</span>, $prefix=<span class="Constant">Null</span>, $dir=<span class="Constant">False</span>)
{
    <span class="Statement">if</span> ($template === <span class="Constant">Null</span>)
        $template = <span class="Constant">'XXXXXX'</span>;
    <span class="Statement">if</span> ($prefix === <span class="Constant">Null</span>)
        $prefix = sys_get_temp_dir();

    <span class="Comment"># Check if we can write to $prefix, we will *not* create this directory!</span>
    $oprefix = $prefix;
    $prefix = realpath($prefix);
    <span class="Statement">if</span> ($prefix === <span class="Constant">False</span> || !is_dir($prefix))
        <span class="Statement">throw</span> <span class="Statement">new</span> MktempError(<span class="Constant">&quot;Prefix `</span>$oprefix<span class="Constant">' doesn't exists or isn't a directory&quot;</span>);
    <span class="Statement">if</span> (!is_writable($prefix))
        <span class="Statement">throw</span> <span class="Statement">new</span> MktempError(<span class="Constant">&quot;Prefix `</span>$prefix<span class="Constant">' isn't writable&quot;</span>);

    <span class="Comment"># Some sanity checks in $template</span>
    <span class="Statement">if</span> (strpos($template, <span class="Constant">'/'</span>) !== <span class="Constant">False</span>)
        <span class="Statement">throw</span> <span class="Statement">new</span> MktempException(<span class="Constant">&quot;Template `</span>$template<span class="Constant">' contains a slash (/) character&quot;</span>);
    <span class="Statement">if</span> (strlen($template) &gt; PHP_MAXPATHLEN)
        <span class="Statement">throw</span> <span class="Statement">new</span> MktempException(<span class="Constant">&quot;Template `</span>$template<span class="Constant">' is longer than PHP_MAXPATHLEN&quot;</span>);

    <span class="Comment"># Replacement characters for the X's</span>
    $padchars = <span class="Constant">&quot;0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz&quot;</span>;

    <span class="Comment"># Replace two or more XX's with a random choice from $padchars</span>
    $name = <span class="Constant">''</span>;
    $doreplace = <span class="Constant">False</span>;
    $Xs = [];
    <span class="Statement">foreach</span> (range(<span class="Constant">0</span>, strlen($template)) <span class="Statement">as</span> $i) {
        $c = substr($template, $i, <span class="Constant">1</span>);
        <span class="Statement">if</span> ($c !== <span class="Constant">'X'</span>)
            $doreplace = <span class="Constant">False</span>;
        <span class="Statement">elseif</span> ($c === <span class="Constant">'X'</span> &amp;&amp; substr($template, $i + <span class="Constant">1</span>, <span class="Constant">1</span>) === <span class="Constant">'X'</span>)
            $doreplace = <span class="Constant">True</span>;

        <span class="Statement">if</span> ($doreplace) {
            $c = $padchars[mt_rand(<span class="Constant">0</span>, strlen($padchars) - <span class="Constant">1</span>)];
            $Xs[] = $i;
        }

        $name .= $c;
    }

    <span class="Statement">if</span> (count($Xs) === <span class="Constant">0</span>)
        <span class="Statement">throw</span> <span class="Statement">new</span> MktempError(<span class="Constant">&quot;No sequence of two or more X characters in template `</span>$template<span class="Constant">'&quot;</span>);

    $maxpermutations = pow(strlen($padchars), count($Xs));
    $permutation = <span class="Constant">0</span>;
    $curpos = array_shift($Xs);
    $startchr = strpos($padchars, substr($name, $curpos, <span class="Constant">1</span>)) - <span class="Constant">1</span>;
    $trychr = $startchr;
    <span class="Statement">while</span> (<span class="Constant">true</span>) {
        <span class="Statement">if</span> ($permutation &gt;= $maxpermutations)
            <span class="Statement">throw</span> <span class="Statement">new</span> MktempError(<span class="Constant">&quot;Unable to create </span>$prefix<span class="Constant">/</span>$template<span class="Constant">; all possible file permutations already exist&quot;</span>);

        <span class="Comment"># Try to create file/directory</span>
        <span class="Statement">if</span> ($dir) {
            $s = @mkdir(<span class="Constant">&quot;</span>$prefix<span class="Constant">/</span>$name<span class="Constant">&quot;</span>, <span class="Constant">0700</span>);

            <span class="Comment"># What we *really* want to do is do something along the lines of</span>
            <span class="Comment"># `errno == EEXISTS' in C. In PHP there is, as far as I can see, no</span>
            <span class="Comment"># way to do this.</span>
            <span class="Comment"># The only thing we can do is run error_get_last(), and get a text</span>
            <span class="Comment"># message, which is locale-dependent and may change in future PHP</span>
            <span class="Comment"># versions.</span>
            <span class="Comment">#</span>
            <span class="Comment"># This check is needed, because all sort of things can go wrong (</span>
            <span class="Comment"># permissions of $prefix changed, signal caught, symlink loop, max</span>
            <span class="Comment"># file descriptors, etc).</span>
            <span class="Comment">#</span>
            <span class="Comment"># The file_exists() sort of solves the problem, I can't think of any</span>
            <span class="Comment"># serious drawbacks, but it's extra disk I/O, and in very, *VERY*</span>
            <span class="Comment"># rare cases it's not reliable (fopen() failed for another reason &amp;</span>
            <span class="Comment"># this file is created before we arrive at this check)</span>
            <span class="Comment">#</span>
            <span class="Comment"># There's a bug for this, but it doesn't seem to be considered much</span>
            <span class="Comment"># of a priority...  https://bugs.php.net/bug.php?id=49396</span>
            <span class="Statement">if</span> (!$s &amp;&amp; file_exists(<span class="Constant">&quot;</span>$prefix<span class="Constant">/</span>$name<span class="Constant">&quot;</span>)) {
                $err = error_get_last();
                <span class="Statement">throw</span> <span class="Statement">new</span> MktempError(<span class="Constant">&quot;Error creating `</span>$prefix<span class="Constant">/</span>$name<span class="Constant">': </span>{$err[<span class="Constant">'message'</span>]}<span class="Constant">&quot;</span>);
            }
            <span class="Statement">if</span> ($s) <span class="Statement">break</span>;
        }
        <span class="Statement">else</span> {
            $s = @fopen(<span class="Constant">&quot;</span>$prefix<span class="Constant">/</span>$name<span class="Constant">&quot;</span>, <span class="Constant">'x'</span>);

            <span class="Statement">if</span> ($s === <span class="Constant">False</span> &amp;&amp; !file_exists(<span class="Constant">&quot;</span>$prefix<span class="Constant">/</span>$name<span class="Constant">&quot;</span>)) {
                $err = error_get_last();
                <span class="Statement">throw</span> <span class="Statement">new</span> MktempError(<span class="Constant">&quot;Error creating `</span>$prefix<span class="Constant">/</span>$name<span class="Constant">': </span>{$err[<span class="Constant">'message'</span>]}<span class="Constant">&quot;</span>);
            }

            <span class="Statement">if</span> ($s !== <span class="Constant">False</span>) {
                fclose($s);
                chmod(<span class="Constant">&quot;</span>$prefix<span class="Constant">/</span>$name<span class="Constant">&quot;</span>, <span class="Constant">0600</span>);
                <span class="Statement">break</span>;
            }
        }

        <span class="Comment"># Loop over each X we replaced, and try the next character from</span>
        <span class="Comment"># $padchars</span>
        $permutation += <span class="Constant">1</span>;
        $trychr += <span class="Constant">1</span>;
        <span class="Statement">if</span> ($trychr &gt; strlen($padchars) - <span class="Constant">1</span>)
            $trychr = <span class="Constant">0</span>;

        <span class="Statement">if</span> ($trychr === $startchr) {
            $curpos = array_shift($Xs);
            $startchr = strpos($padchars, substr($name, $curpos, <span class="Constant">1</span>)) - <span class="Constant">1</span>;
            $trychr = $startchr + <span class="Constant">1</span>;
        }

        $name = substr_replace($name, $padchars[$trychr], $curpos, <span class="Constant">1</span>);
    }

    <span class="Statement">return</span> <span class="Constant">&quot;</span>$prefix<span class="Constant">/</span>$name<span class="Constant">&quot;</span>;
}

<span class="Statement">class</span> MktempError <span class="Statement">extends</span> Exception { }
