#!/bin/sh

set -eu
IFS="
"

project=$1

cd "/data/code/$project"

# Setup server
hg serve --port 8001 --style mine --accesslog /dev/null &
serve=$!
c() {
	kill $serve
}
trap c EXIT INT
sleep 2

out="/data/code/arp242.net/code/$project"
# Get header
header=$(sed $(( 1 + $(grep -n ^---$ "$out/index.markdown" | cut -d: -f1 | tail -n1) )),50000d "$out/index.markdown")

# Write with header
write() {
	echo "$header" > $2
	echo "{% raw %}" >> $2
	echo "$1" | sed "s/%%codeproject%%/$project/g" >> $2
	echo "{% endraw %}" >> $2
}

# Tags
write "$(curl -s 'http://localhost:8001/tags')" "$out/downloads.html" 

# Commits
#mkdir -p "$out/commits"
#write "$(curl -s 'http://localhost:8001/graph/tip?revcount=5000')" "$out/commits/index.html"
#for line in $(curl -s 'http://localhost:8001/shortlog/tip?revcount=5000'); do
#	write "$(curl -s "http://localhost:8001/rev/$line")" "$out/commits/$line.html"
#done

# Files
hg_ls() {
	local root=$1

	mkdir -p "$out/browse$root"
	write "$(curl -s "http://localhost:8001/file/tip$root")" "$out/browse${root}index.html"

	# Get list of files
	local f
	for f in $(grep -E 'href=".*?/browse/.*?"' "$out/browse${root}index.html" | sed -E 's|<a href=".*?/browse/(.*?)">|\1|' | uniq); do
		# dir
		if [ "$(echo -n "$f" | tail -c1)" = "/" ]; then
			hg_ls "$f"
		# file
		else
			# TODO: jekyl doesn't copy files starting with . or _

			write "$(curl -s "http://localhost:8001/file/tip/${f%.html}")" "$out/browse/$f"
			# TODO: Get file log
			#http://localhost:8000/log/tip/download-npo?revcount=5000
			# TODO: Raw file
			#http://localhost:8000/raw-file/tip/diffexpr.vim
		fi
	done
}

#mkdir -p "$out/browse"
#hg_ls /
